apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-2
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi