apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: tomasoares/fibonacci-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'
    - image: tomasoares/fibonacci-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: tomasoares/fibonacci-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/dev/database-persistent-volume-claim.yaml
      - k8s/dev/database-persistent-volume.yaml
      - k8s/ingress-service.yaml
      - k8s/postgres-cluster-ip-service.yaml
      - k8s/postgres-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-cluster-ip-service.yaml
        