apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: fibonacci-docker-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonacci-docker.com
  dnsNames:
    - fibonacci-docker.com
    - www.fibonacci-docker.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fibonacci-docker.com
          - www.fibonacci-docker.com